name: docker-publish-frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar projeto do GitHub
        uses: actions/checkout@v3

      - name: Fazer login no Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Gerar imagem Docker do frontend
        run: docker build -t andersonluizdealmeida1997/almeida-pinturas-frontend:latest .

      - name: Tag a imagem com a versão do commit
        run: |
          docker tag andersonluizdealmeida1997/almeida-pinturas-frontend:latest andersonluizdealmeida1997/almeida-pinturas-frontend:${{ github.sha }}

      - name: Enviar imagem (latest) pro Docker Hub
        run: docker push andersonluizdealmeida1997/almeida-pinturas-frontend:latest

      - name: Enviar versão específica pro Docker Hub
        run: docker push andersonluizdealmeida1997/almeida-pinturas-frontend:${{ github.sha }}
